### ISSUE TITLE
Scrolling doesn't trigger bubbles scale animation

### ISSUE THREAD

**Issue by alexandruionascu** [blakesanie/React-Bubble-UI#1]
Hello,

I'm trying to replicate the example but the elements during scrolling are not scaling up. They remain the same size as in the screenshot.
I was wondering if you know what would cause the issue here.

![image](https://user-images.githubusercontent.com/5594522/106467853-e340fa80-64a5-11eb-964c-04857089f6d9.png)

**Comment by blakesanie** [comment]
Hello,

Make sure the bubble UI element has the proper styles. Try using a fixed width and height instead of units like vw and vh. Also, make sure the correct container is scrolling (I.e. is the bubbleUI element itself overflowing its parent container?

Best of luck,


Blake Sanie

**Comment by alexandruionascu** [comment]
Found the issue, it works on React ^16.13.1, I tried on React 17 and this issue occurs. Will go into the details to see what caused the problem.

Later edit: onScroll event no longer bubbles in React 17. Pretty sure that's the problem.

**Comment by Dave93** [comment]
Could you help to fix this issue?

**Comment by blakesanie** [comment]
Thanks for noticing this! I updated the library to work properly with React 17 [here](https://github.com/blakesanie/React-Bubble-UI/commit/574272d3a062330f26ccf597e6b20a5e41864b13). Let me know if there are any other issues!
